name: Build, Release APK and Screenshots

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump version (auto-increment)
      id: bump_version
      run: |
        # Получаем текущую версию
        CURR_VERSION=$(grep -oP 'versionName\s+"\K[^"]+' app/build.gradle)
        CURR_CODE=$(grep -oP 'versionCode\s+\K[0-9]+' app/build.gradle)
        # Инкрементируем patch (x.y -> x.(y+1))
        MAJOR=$(echo $CURR_VERSION | cut -d. -f1)
        MINOR=$(echo $CURR_VERSION | cut -d. -f2)
        if [ -z "$MINOR" ]; then MINOR=0; fi
        NEW_MINOR=$((MINOR+1))
        NEW_VERSION="$MAJOR.$NEW_MINOR"
        NEW_CODE=$((CURR_CODE+1))
        # Обновляем build.gradle
        sed -i "s/versionName \"$CURR_VERSION\"/versionName \"$NEW_VERSION\"/" app/build.gradle
        sed -i "s/versionCode $CURR_CODE/versionCode $NEW_CODE/" app/build.gradle
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "new_code=$NEW_CODE" >> $GITHUB_OUTPUT
        echo "Version bumped: $CURR_VERSION → $NEW_VERSION ($CURR_CODE → $NEW_CODE)"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/build.gradle
        git commit -m "🔖 Bump version to $NEW_VERSION ($NEW_CODE) [auto]" || echo "No version change to commit"
        git push || echo "No changes to push"

    - name: Generate release notes
      id: release_notes
      run: |
        echo "## Changelog for v${{ steps.bump_version.outputs.new_version }}" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Последние коммиты:" >> RELEASE_NOTES.md
        git log -10 --pretty=format:"- %s (%an)" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Изменения из CHANGELOG.md:" >> RELEASE_NOTES.md
        tail -n 20 docs/CHANGELOG.md >> RELEASE_NOTES.md
        cat RELEASE_NOTES.md

    - name: Commit release notes
      run: |
        git add RELEASE_NOTES.md
        git commit -m "📝 Update release notes [auto]" || echo "No release notes change to commit"
        git push || echo "No changes to push"

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Get version name
      id: version
      run: |
        VERSION=$(grep -oP 'versionName\s+"\K[^"]+' app/build.gradle)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

    - name: Copy APK to releases folder
      run: |
        mkdir -p releases/debug
        ls -la app/build/outputs/apk/debug/
        cp app/build/outputs/apk/debug/app-debug.apk releases/debug/
        cd releases/debug
        ls -la
        rm latest-debug.apk
        # Переименовываем с версией и датой
        newname="FinancialSuccess-v${{ steps.version.outputs.version }}-${{ steps.date.outputs.date }}-debug.apk"
        mv -f app-debug.apk "$newname"
        echo "app-debug.apk renamed to: $newname"
        ln -sf "$newname" "latest-debug.apk"
        ls -la

    - name: Clean up old APKs (keep only 3 latest)
      run: |
        cd releases/debug
        ls -tp FinancialSuccess-v*-debug.apk | grep -v '/$' | tail -n +4 | xargs -r rm --
        ls -la

    - name: Commit APK files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add releases/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📱 Auto-commit APK v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}
          
          🔧 Build info:
          - Version: ${{ steps.version.outputs.version }}
          - Date: ${{ steps.date.outputs.date }}
          - Branch: ${{ github.ref_name }}
          - Commit: ${{ github.sha }}"
          git push
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.bump_version.outputs.new_version }}-${{ steps.date.outputs.date }}
        name: "🎮 Financial Success v${{ steps.bump_version.outputs.new_version }}"
        body_path: RELEASE_NOTES.md
        files: |
          releases/debug/*.apk
        draft: false
        prerelease: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinancialSuccess-v${{ steps.version.outputs.version }}-${{ steps.date.outputs.date }}
        path: releases/debug/*.apk

    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"
        maestro --version

    - name: Start Android Emulator (Phone)
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        script: |
          adb shell input keyevent 82
          adb shell input keyevent 82

    - name: Install APK on Phone Emulator
      run: |
        export PATH="$PATH":"$HOME/.maestro/bin"
        adb install app/build/outputs/apk/debug/app-debug.apk
        adb shell pm list packages | grep financialsuccess

    - name: Create screenshots directory
      run: |
        mkdir -p screenshots/phone
        mkdir -p screenshots/tablet

    - name: Run Maestro Screenshots (Phone)
      run: |
        export PATH="$PATH":"$HOME/.maestro/bin"
        maestro test maestro/screenshots.yaml --format junit --output screenshots/phone/
        echo "Phone screenshots completed!"

    - name: Start Android Emulator (Tablet)
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 10
        script: |
          adb shell input keyevent 82
          adb shell input keyevent 82

    - name: Install APK on Tablet Emulator
      run: |
        export PATH="$PATH":"$HOME/.maestro/bin"
        adb install app/build/outputs/apk/debug/app-debug.apk
        adb shell pm list packages | grep financialsuccess

    - name: Run Maestro Screenshots (Tablet)
      run: |
        export PATH="$PATH":"$HOME/.maestro/bin"
        maestro test maestro/screenshots-tablet.yaml --format junit --output screenshots/tablet/
        echo "Tablet screenshots completed!"

    - name: List generated screenshots
      run: |
        echo "📱 Phone screenshots:"
        ls -la screenshots/phone/
        echo ""
        echo "📱 Tablet screenshots:"
        ls -la screenshots/tablet/

    - name: Upload Screenshots Artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-v${{ steps.version.outputs.version }}
        path: screenshots/

    - name: Commit Screenshots to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add screenshots/
        if git diff --staged --quiet; then
          echo "No screenshots to commit"
        else
          git commit -m "📸 Auto-generated screenshots v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}
          
          📱 Screenshots:
          - Phone: $(ls screenshots/phone/*.png | wc -l) files
          - Tablet: $(ls screenshots/tablet/*.png | wc -l) files
          - Total: $(find screenshots/ -name "*.png" | wc -l) files"
          git push
        fi

    - name: Update Release with Screenshots
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.bump_version.outputs.new_version }}-${{ steps.date.outputs.date }}
        files: |
          screenshots/phone/*.png
          screenshots/tablet/*.png
        draft: false
        prerelease: false